name: rebuild pdf
on: [push]
jobs:
  Rebuild-PDF:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Environment
      - run: wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu && chmod +x ./install-tl-ubuntu
      - run: sudo ./install-tl-ubuntu
      - run: export PATH="/opt/texbin:$PATH"
      - run: tex -v
      - run: sudo mkdir -p /usr/share/fonts/opentype/
      - run: sudo mv ./fonts/AdobeFangsongStd-Regular.otf /usr/share/fonts/opentype/
      - run: sudo mv ./fonts/AdobeHeitiStd-Regular\ \(v5.010\).otf /usr/share/fonts/opentype/
      - run: sudo mv ./fonts/AdobeKaitiStd-Regular\ \(v5.010\).otf /usr/share/fonts/opentype/
      - run: sudo mv ./fonts/AdobeSongStd-Light\ \(v5.010\).otf /usr/share/fonts/opentype/
      - run: sudo mkfontscale
      - run: sudo mkfontdir
      - run: sudo fc-cache -fv
      - run: fc-list :lang=zh
      - run: sudo apt-get install python-pygments
      - name: Build
      - run: make
      - name: Submit new PDF
      - run: make clean
      - run: git checkout master
      - run: git add tcp.pdf
      - run: git config user.name "Github Actions bot"
      - run: git config user.email "github-actions-bot@not.exist.email.address"
      - run: git commit -m "[ci skip] auto generate tex.pdf" 
      - run: git push --force "https://${{secrets.GH_TOKEN}}@github.com/fzyz999/Analysis_TCP_in_Linux" master:master
