name: rebuild pdf
on: [push]
jobs:
  Rebuild-PDF:
    runs-on: ubuntu-latest
    steps:
      # - run: wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu && chmod +x ./install-tl-ubuntu
      # - run: sudo ./install-tl-ubuntu
      # - run: export PATH="/opt/texbin:$PATH"
      - run: sudo apt install texlive-full
      - run: tex -v
      - run: sudo mkdir -p /usr/share/fonts/opentype/
      - uses: actions/checkout@v3
        with:
          token: '${{secrets.GH_TOKEN}}'
      - run: |
          sudo mv ./fonts/AdobeFangsongStd-Regular.otf /usr/share/fonts/opentype/
          sudo mv ./fonts/AdobeHeitiStd-Regular\ \(v5.010\).otf /usr/share/fonts/opentype/
          sudo mv ./fonts/AdobeKaitiStd-Regular\ \(v5.010\).otf /usr/share/fonts/opentype/
          sudo mv ./fonts/AdobeSongStd-Light\ \(v5.010\).otf /usr/share/fonts/opentype/
          sudo mkfontscale
          sudo mkfontdir
          sudo fc-cache -fv
          fc-list :lang=zh
          sudo apt-get install python-pygments
          make
          make clean
          git checkout master
          git add tcp.pdf
          git config user.name "Github Actions bot"
          git config user.email "github-actions-bot@not.exist.email.address"
          git commit -m "[ci skip] auto generate tex.pdf" 
          git push --force "https://${{secrets.GH_TOKEN}}@github.com/fzyz999/Analysis_TCP_in_Linux" master:master
